import org.hibernate.Session;
import org.hibernate.Transaction;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {
		System.out.println("Hello world.\n");
		
		getFromDB();
	}

	static public void putToDB() {
		Session session = null;
		Transaction transaction = null;
		try {
			session = HibernateUtil.getSessionFactory().openSession();
			transaction = session.getTransaction();
			transaction.begin();

			Car maruti = new Car();
			maruti.setId(104);
			maruti.setName("Ritz");

			session.save(maruti);

			transaction.commit();
		} catch (Exception e) {
			if (transaction != null) {
				transaction.rollback();
			}
			e.printStackTrace();
		} finally {
			if (session != null) {
				session.close();
			}
		}

		HibernateUtil.shutdown();

	}

	static public void getFromDB() {
		Session session = null;
		Transaction transaction = null;
		try {
			session = HibernateUtil.getSessionFactory().openSession();
			transaction = session.getTransaction();
			transaction.begin();

			// Obtain an entity using get() method
			Car car1 = session.get(Car.class, 101);
			if (car1 != null) {
				System.out.println(car1.toString());
			}

			// Obtain an entity using load() method
			Car car2 = session.load(Car.class, 102);
			System.out.println(car2.toString());

			// Obtain an entity using byId() method
			Car car3 = session.byId(Car.class).getReference(103);
			System.out.println(car3.toString());

			transaction.commit();
		} catch (Exception e) {
			if (transaction != null) {
				transaction.rollback();
			}
			e.printStackTrace();
		} finally {
			if (session != null) {
				session.close();
			}
		}

		HibernateUtil.shutdown();
	}
}
